[package]
name = "rusty-pullauta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
imageproc = "0.23.0"
rand = "0.8.5"
regex = "1"
rust-ini = "0.18.0"
zip = "0.6.6"
