[package]
name = "rusty-pullauta"
version = "1.0.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
imageproc = "0.23.0"
las = { version = "0.8", features = ["laz"] }
rand = "0.8.5"
regex = "1"
rust-ini = "0.18.0"
shapefile = "0.6.0"
skia-safe = "0.72.0"
zip = "0.6.6"
