[package]
name = "rusty-pullauta"
version = "1.0.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version ="0.25", default-features = false, features = [
	"rayon",
	"png",
	"jpeg",
]}

imageproc = { version = "0.25.0", default-features = false, features = [
	"rayon",
]}

las = { version = "0.8", features = ["laz"] }
rand = "0.8.5"
regex = "1"
rust-ini = "0.21"
shapefile = "0.6.0"
skia-safe = "0.73"
zip = "0.6.6"
